---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.0.1"
    hooks:
      - id: "no-commit-to-branch"
        args: ["--branch", "main"]
      - id: "check-merge-conflict"
      - id: "trailing-whitespace"
      - id: "mixed-line-ending"
      - id: "end-of-file-fixer"
      - id: "check-yaml"
        args: ["--unsafe"]

  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: "v1.26.3"
    hooks:
      - id: "yamllint"
        args: ["--format", "parsable", "--strict"]

  - repo: "https://github.com/jumanjihouse/pre-commit-hook-yamlfmt"
    rev: "0.1.0"
    hooks:
      - id: "yamlfmt"
        args: ["--mapping", "2", "--sequence", "4", "--offset", "2", "--preserve-quotes"]
        exclude: ".*"

  - repo: "https://github.com/mattlqx/pre-commit-search-and-replace"
    rev: "v1.0.5"
    hooks:
      - id: "search-and-replace"

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
      - id: reorder-python-imports
        name: Reorder python imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--application-directories=custom_components]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier