lovelace_minimalist_ui:
  !include plugins/lovelace_minimalist_ui.yaml

button_card_templates:
  !include_dir_merge_named ../__minimalist_ui__/button-cards-templates/

title: Lovelace Minimalist UI
# theme: minimalist-desktop
theme: ios-dark-mode
views:
  - cards:
      - type: custom:button-card
        entity: sensor.time
      - type: custom:button-card
        template: chip_right