button_card_templates:
  !include_dir_merge_named button-cards-templates/
  # !include /config/lovelace_minimalist_ui/language.yaml
  # !include_dir_merge_named /config/lovelace_minimalist_ui/cards

title: Lovelace Minimalist UI
# theme: minimalist-desktop
theme: ios-dark-mode
views:
  - cards:
      - type: custom:button-card
        entity: sensor.time