---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  - title: "Example View"
    path: 0
    icon: "mdi:flower"
    cards:
      - type: "vertical-stack"
        cards:
          - type: "custom:button-card"
            template: "card_title"
            name: "Congrats with your installation 🎉"
            label: "Explore here some of the wonderfull 'Minimalistic-UI' cards we offer"
          - type: "markdown"
            content: >
              # Welcome {{ user[0]|upper}}{{user[1:] }}
          - type: "custom:auto-entities"
            card:
              type: "grid"
              columns: 1
              square: false
            card_param: "cards"
            sort:
              count: 1
            filter:
              include:
                - domain: "weather"
                  options:
                    type: "weather-forecast"
          - type: "custom:button-card"
            template: "card_title"
            name: "Lights"
            label: "These are your 'Minimalist' light cards"
          - type: "custom:auto-entities"
            card:
              type: "grid"
              columns: 2
              square: false
            card_param: "cards"
            sort:
              count: 4
            filter:
              include:
                - domain: "light"
                  options:
                    type: "custom:button-card"
                    template: "card_light"
                    variables:
                      ulm_card_light_enable_slider: true
                      ulm_card_light_enable_color: true
                      ulm_card_light_enable_popup: true
          - type: "custom:button-card"
            template: "card_title"
            name: "Binary Sensors"
            label: "These are your 'Minimalist' binary_sensor cards"
          - type: "custom:auto-entities"
            card:
              type: "grid"
              columns: 2
              square: false
            card_param: "cards"
            sort:
              count: 4
            filter:
              include:
                - domain: "binary_sensor"
                  options:
                    type: "custom:button-card"
                    template: "card_binary_sensor_alert"
                    variables:
                      - ulm_card_binary_sensor_alert: true
                    show_last_changed: true
          - type: "custom:button-card"
            template: "card_title"
            name: "Sensors"
            label: "These are your 'Minimalist' sensors card"
          - type: "custom:auto-entities"
            card:
              type: "grid"
              columns: 2
              square: false
            card_param: "cards"
            sort:
              count: 4
            filter:
              include:
                - domain: "sensor"
                  options:
                    type: "custom:button-card"
                    template: "card_generic"
          - type: "custom:button-card"
            template: "card_title"
            name: "Batteries"
            label: "These are your 'Minimalist' battery cards"
          - type: "custom:auto-entities"
            card:
              type: "grid"
              columns: 2
              square: false
            card_param: "cards"
            sort:
              count: 4
            filter:
              include:
                - attributes:
                    unit_of_measurement: "%"
                    device_class: "battery"
                  options:
                    type: "custom:button-card"
                    template: "card_battery"
                    variables:
                      ulm_card_battery_battery_state_entity_id: "this.entity_id"
                      ulm_card_battery_battery_level_danger: 30
                      ulm_card_battery_battery_level_warning: 80
