---
name: "Manage labels"

on:
  push:
    branches: ["main", "dev"]

jobs:
  labeler:
    name: "Labeler"
    runs-on: "ubuntu-latest"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: "actions/checkout@v2"
      - name: "\U0001F680 Run Labeler"
        uses: "crazy-max/ghaction-github-labeler@v3.1.1"
        with:
          skip-delete: true
